services:
  - type: web
    name: pudpredict
    env: python
    plan: free
    buildCommand: "./build.sh"
    startCommand: "gunicorn pudpredict.wsgi:application"
    envVars:
      - key: DEBUG
        value: "False"
      - key: DATABASE_URL
        fromDatabase:
          name: pudpredict-db
          property: connectionString
      - key: SECRET_KEY
        generateValue: true
      - key: ALLOWED_HOSTS
        value: ".onrender.com"
      - key: CSRF_TRUSTED_ORIGINS
        value: "https://*.onrender.com"
      - key: EMAIL_BACKEND
        value: "django.core.mail.backends.smtp.EmailBackend"
      - key: EMAIL_HOST
        value: "smtp.gmail.com"
      - key: EMAIL_PORT
        value: "587"
      - key: EMAIL_USE_TLS
        value: "True"
      - key: EMAIL_HOST_USER
        sync: false
      - key: EMAIL_HOST_PASSWORD
        sync: false
      - key: DEFAULT_FROM_EMAIL
        sync: false
      - key: EMAIL_VERIFICATION_MAX_AGE
        value: "86400"

databases:
  - name: pudpredict-db
    plan: free
