# Generated by Django 5.2.14 on 2026-05-12 22:05

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patients', '0003_assessment_health_metrics'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ClinicalReference',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('source', models.CharField(default='PubMed', max_length=40)),
                ('query', models.CharField(max_length=255)),
                ('title', models.CharField(max_length=500)),
                ('url', models.URLField(blank=True)),
                ('published', models.CharField(blank=True, max_length=80)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='DrugSafetyWarning',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('medication', models.CharField(max_length=120)),
                ('warning', models.TextField()),
                ('source_url', models.URLField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddField(
            model_name='assessment',
            name='complications',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='assessment',
            name='diagnosis',
            field=models.CharField(blank=True, max_length=160),
        ),
        migrations.AddField(
            model_name='assessment',
            name='drug_warnings',
            field=models.JSONField(default=list),
        ),
        migrations.AddField(
            model_name='assessment',
            name='is_pud_positive',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='assessment',
            name='medications',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='assessment',
            name='predicted_ulcer_type',
            field=models.CharField(default='Not indicated', max_length=80),
        ),
        migrations.AddField(
            model_name='assessment',
            name='prediction_details',
            field=models.JSONField(default=dict),
        ),
        migrations.AddField(
            model_name='assessment',
            name='research_references',
            field=models.JSONField(default=list),
        ),
        migrations.CreateModel(
            name='PUDDatasetUpload',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to='datasets/')),
                ('original_filename', models.CharField(max_length=255)),
                ('row_count', models.PositiveIntegerField(default=0)),
                ('column_profile', models.JSONField(default=dict)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('processed', 'Processed'), ('failed', 'Failed')], default='pending', max_length=16)),
                ('message', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pud_dataset_uploads', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
